### ISSUE TITLE
Safari tab groups can't be clicked

### ISSUE THREAD

**Issue by eproxus** [dexterleng/homerow#12]
**Describe the bug**

When showing the tab groups sidebar in Safari (_View_ → _Show Sidebar_), the tab groups can't be selected with Homerow ([Jumpers 2 Preview](https://github.com/dexterleng/homerow/issues/6#issuecomment-1321086255)). Only the dropdown that opens up the tab group can be clicked. Using the mouse, the tab group itself can be clicked and switched to.

(Vimac/Shortcat can hit these).

**Steps to reproduce the bug**

1. Open Safari
2. Check _View_ → _Show Sidebar_ to make sure the sidebar is enabled
3. Create at least one tab group
4. Try to click it using Homerow's jump feature
5. Notice that only the dropdown (which expands the tab group) is clickable, but not the tab group itself

**Comment by dexterleng** [comment]
Fixed in Alpha 12. Closing this now!
