### ISSUE TITLE
Cannot exit out of Homerow after shift+enter to simulate right-click in Slack

### ISSUE THREAD

**Issue by brettflorio** [dexterleng/homerow#14]
**Describe the bug**

This seems to be _very_ specific, at least in my testing, but noting in case it's helpful. Happens with Homerow version a68dcbe (alpha -1), from #6 ([homerow-jumpers-3-preview.zip](https://github.com/dexterleng/homerow/files/10072968/homerow-jumpers-3-preview.zip)) and Slack Version 4.29.144 on macOS 13.0.1.

I thought maybe it was an issue with Electron apps, but VS Code doesn't seem 

**Steps to reproduce the bug**

1. When using Homerow to select a Slack message timestamp and shift+enter to right-click. That works fine, and results in this: \
    <img width="207" alt="image" src="https://user-images.githubusercontent.com/34131/204036691-e086c7e1-0ff0-4b66-a92f-87a64a0b7b89.png">
1. Using the keyboard at that point (down arrow, enter to copy link) works fine. However, _after_ hitting shift+enter…
1. The Homerow focus won't go away. Hitting escape, tab, enter, or almost any other key results in the little error noise. \
    <img width="208" alt="image" src="https://user-images.githubusercontent.com/34131/204038217-0bc9be64-00c6-4361-9f31-fa6bf4054cca.png">
1. Switching apps (via mouse or cmd+tab) then going back to Slack _looks_ like the Homerow focus is still there, but typing works as normal within Slack again.

**Comment by dexterleng** [comment]
Seems to only happen with the classic workflow. Working on a fix!

**Comment by dexterleng** [comment]
mind helping check if preview-4 addresses the issue?

https://github.com/dexterleng/homerow/issues/6#issuecomment-1321086255

**Comment by brettflorio** [comment]
@dexterleng Yup! Or rather, I tried preview-5. Fixes the issue! Thanks!

Fwiw, the blue highlight/focus indicator remains, but it doesn't hijack the keyboard, and once you do anything else, the focus indicator disappears. Not an issue, just noting in case it's of interest.
