### ISSUE TITLE
Keyboard Scrolling in the New Homerow

### ISSUE THREAD

**Issue by brettflorio** [dexterleng/homerow#15]
**Is your feature suggestion related to a problem? Please describe.**

It would be wonderful to get the scrolling-via-keyboard from the original Homerow added back to New Homerow. This has been brought up in other tickets, but #6 is only about the new "jumper" functionality (which is great), so it feels odd to hijack that.

**Describe the solution you'd like**

The ability to scroll via keyboard shortcuts, just like in the original Homerow.

**Describe alternatives you've considered**

I'm currently running both the old and new Homerow apps at the same time. The new Homerow's jumper functionality is awesome, but I'll keep the old Homerow running until I can do keyboard-based scrolling in the new app :)

**Comment by tadassce** [comment]
Hi @brettflorio, it seems that @dexterleng has decided to split the scrolling feature into a separate mini app:

https://github.com/dexterleng/KeyboardScroller.docs

It's mentioned in [the readme](https://github.com/dexterleng/homerow#pro-tip-scrolling-with-keyboard-scroller).

**Comment by javid-g** [comment]
It would be nice to keep the scrolling feature in the same app (new Homerow) if possible!

**Comment by brettflorio** [comment]
@tadassce Ah, thanks so much. Totally missed that!

Like @javid-g mentioned, I wouldn't mind it in the same app. The keyboard scrolling is actually the "killer feature" that got me into Homerow in the first place, and my hunch is folks who like Homerow also would love KeyboardScroller, but so long as it works, doesn't really matter if it's a separate app (to me).

**Comment by al3xandru** [comment]
I bought Homerow in the first place for the scrolling functionality. As it currently stands, the original/old app cannot be run in parallel with the new one. 

KeyboardScroller is not modal and using normal shortcuts for scrolling could be achieved with many other apps (Karabiner, Keyboard Maestro, Hammerspoon). The 2 approaches are not equivalent.

@brettflorio could you reopen the ticket to avoid creating a new one?

**Comment by brettflorio** [comment]
@al3xandru That's probably more a question @dexterleng, but my hunch is it might make more sense to open a ticket in KeyboardScroller to discuss.
