### ISSUE TITLE
Please add settings for 1) lowercased click area identifiers 2) automatic click on entering lowercase identifiers. 

### ISSUE THREAD

**Issue by backward-crazy-mage-puppy-36** [dexterleng/homerow#17]
Hi, 
Using Homerow on M1 Ventura.
Having the yellow click area identifiers show up with lowercase letters, and
automatic click (no need to press enter key) when these lowercase characters are entered 
will make for a faster workflow that users can opt in for.
Thanks.

**Comment by dexterleng** [comment]
@backward-crazy-mage-puppy-36 have you tried using the classic workflow option? You still have to press enter though. 

Not sure how to do modifier clicks without <modifier> + Enter

**Comment by skobylite** [comment]
Same here - perhaps could auto-click when once the selector is narrowed down to no alternative options. In that situation, pressing enter is redundant 👌

**Comment by ryan-efendy** [comment]
+1 As a user I would like an option to not have to press `Enter` to perform a click on the focused UI element.

**Comment by srikat** [comment]
Asked the same here: https://twitter.com/srikat/status/1609375111374843905.

**Comment by zsmatrix62** [comment]
is it possible to search label using lower case?

**Comment by dexterleng** [comment]
@zsmatrix62 have you tried the classic workflow?

**Comment by dexterleng** [comment]
Hey everyone, I hear your feedback on (1) not having to hold `Shift` to type labels and (2) not having to press `Enter` to click.

Before I consider making drastic changes to the workflow, I've made three changes to address these points. Let me know your thoughts!

1. Labels-only (Classic Workflow)
    - No search, and no need to hold Shift to type labels.
2. I just added a `Press Space to click` option. It's faster and more ergonomic than Return.
    - <img height="500" alt="" src="https://user-images.githubusercontent.com/34204380/211778080-44110834-194a-4053-ac8a-01cb4adfc452.png">
3. I just removed Q, A, B, Z from the label character set. 
    - ![](https://user-images.githubusercontent.com/34204380/211777655-38015678-dcce-4562-8c5d-8cfa182efb62.jpeg)

**Comment by srikat** [comment]
While having Space to also work in addition to Return is useful, it does not address the feature request of automatically following a link when the corresponding hint text is typed w/o any further action imo.

> @zsmatrix62 have you tried the classic workflow?

Just tested this and it works in Classic.

Can you also make it (following label hints using lowercase typing) work (either by default or as an option) in Search & Labels workflow?

**Comment by zsmatrix62** [comment]
> While having Space to also work in addition to Return is useful, it does not address the feature request of automatically following a link when the corresponding hint text is typed w/o any further action imo.
> 
> > @zsmatrix62 have you tried the classic workflow?
> 
> Just tested this and it works in Classic.
> 
> Can you also make it (following label hints using lowercase typing) work (either by default or as an option) in Search & Labels workflow?

Yes, it's working in Classic, I mean if it can be case insensitive that would be fantastic. 🎉

**Comment by dexterleng** [comment]
> While having Space to also work in addition to Return is useful, it does not address the feature request of automatically following a link when the corresponding hint text is typed w/o any further action imo.

Yeah, but I believe it's a step forward that does not require major changes to the workflow, since the Space key is right beneath your thumb.

> Can you also make it (following label hints using lowercase typing) work (either by default or as an option) in Search & Labels workflow?

The workflow needs to disambiguate between (1) searching and (2) typing labels. Holding shift is currently how the distinction is made. I'm not sure how else I can do it.

**Comment by dexterleng** [comment]
@zsmatrix62 

> Yes, it's working in Classic, I mean if it can be case insensitive that would be fantastic. 🎉

I don't understand. It is case insensitive in Classic.

**Comment by etiennepellegrini** [comment]
> The workflow needs to disambiguate between (1) searching and (2) typing labels. Holding shift is currently how the distinction is made. I'm not sure how else I can do it.

Perhaps a workflow where the first string of characters typed is the search, and pressing `Space` switches to following labels? That's what would feel most natural to me

> Yeah, but I believe it's a step forward that does not require major changes to the workflow, since the Space key is right beneath your thumb.

Agreed, thank you for that change. A "Vimac/Vimium" mode where label is clicked immediately would be great (it could work for both Classic and Search workflows). The modifier + click feature could maybe use `Shift` + label (in the classic workflow, and in search if something like the suggestion above replaces the current `Shift` + label

**Comment by goldlil** [comment]
I think it would be great if while typing last letter of label and holding shitt do right click. I would rather to have this than to need to press enter every time I want to click label.

**Comment by dexterleng** [comment]
Just released Alpha 19. You need longer have to press Space or Return to click. You'll need to enable the "Click automatically when label is selected" option.

![CleanShot 2023-04-07 at 17 58 08](https://user-images.githubusercontent.com/34204380/230589043-5d265fef-c75a-41b0-b6dc-56b8a6d59c3c.png)

Let me know if there's any issues!
