### ISSUE TITLE
Bring back scrolling 

### ISSUE THREAD

**Issue by al3xandru** [dexterleng/homerow#20]
I bought Homerow in the first place for the scrolling functionality. The current version of the app is only for clicking. And the original/old app cannot be run in parallel with the new one.

I am aware of the KeyboardScroller app. What it proposes is a different approach though with system wide shortcuts and not  modal. The system shortcuts approach could be achieved with many other apps already (Karabiner, Keyboard Maestro, Hammerspoon).

**Comment by dexterleng** [comment]
I'll add it back eventually. Meanwhile, you could try scrolla: https://twitter.com/scrollaapp

**Comment by iansinnott** [comment]
Ideally homerow could have modes, like Vim, so that `jk` could scroll the active window _unless_ your in an input. Not sure if macos provides APIs to determine if the user is in a text input, but if so that would be great. I.e. do it like Vimium does it.

**Comment by dexterleng** [comment]
> Not sure if macos provides APIs to determine if the user is in a text input, but if so that would be great.

@iansinnott That's something I've wanted as well. Last I checked you need to listen for a `kAXFocusedUIElementChangedNotification` event. The caveat is that unlike Chrome extensions where you can listen to the DOM directly, the accessibility implementation of an app need not mirror what actually happens - so it will not 100% perfect in all cases.

I don't look for perfection - but I do care if edge cases can potentially ruin your experience using your Mac to do normal work. Imagine you are trying to type into the text field with poor accessibility experience and my app triggers a scroll - that seems *really* annoying. For that reason I don't think It's something I will do.

**Comment by dexterleng** [comment]
I think there are only two approaches to go about scrolling:
1. Modality based (Vimac, Scrolla)
2. Hotkey based ([Keyboard Scroller](https://github.com/dexterleng/KeyboardScroller.docs))

I went with (2) when making Keyboard Scroller because I wanted scrolling to be ephemeral - no need to manually enter/exit scrolling, just like with Vimium. I'd like to hear all your thoughts on which workflow you would prefer though!

**Comment by dexterleng** [comment]
Scrolling is back in Alpha 20. 😎. Check it out!

**Comment by DanEEStar** [comment]
It works great! I could finally uninstall the old version of Homerow and use this new version.
Thanks a lot! 🙏

**Comment by jessejanderson** [comment]
Yay!

This is great, but is there any way to turn off the blue-green overlay? I usually turn on scroll mode and keep it on while scrolling and reading so the overlay is kind of unsightly.
