### ISSUE TITLE
Please offer a higher-contrast option for tags, like in 0.12

### ISSUE THREAD

**Issue by nriley** [dexterleng/homerow#23]
**Describe the bug**

The 0.12 version of tags is by far the clearest to use of any version of Homerow/Vimac as the bright yellow tags are easy to scan. The 0.13 version of tags with the darker gradient and arrowheads is harder to read (even though the placement is often improved).

**Screenshots / video**

0.12:
![image](https://user-images.githubusercontent.com/68303/209996046-e1d870bb-f8d1-4508-aaaf-0ea762ae3992.png)
0.13:
![image](https://user-images.githubusercontent.com/68303/209996058-4d3a7620-a6d0-4303-9dbf-e9bcd261bd6a.png)

**Steps to reproduce the bug**

Trigger Homerow particularly on a display supporting HDR — the black on bright yellow "pops" very effectively over the UI, whereas the dim yellow gradient is harder to see.

**Comment by dexterleng** [comment]
I don't mind adding a high-contrast option, or the ability to set custom colors, but if I can provide a one-size-fit-all solution, I would much prefer that.

I tweaked the colors a bit, is this better?

<img width="90" alt="CleanShot 2022-12-30 at 10 44 28@2x" src="https://user-images.githubusercontent.com/34204380/210029306-cbe411da-1d30-45b5-bffb-9dc2efcf0980.png">

[homerow-higher-constrast-labels.app.zip](https://github.com/dexterleng/homerow/files/10322892/homerow-higher-constrast-labels.app.zip)

**Comment by dexterleng** [comment]
Oh and I would also like to note that the default font size in 0.13 is one size smaller than in 0.12.

**Comment by nriley** [comment]
That's an improvement, thanks! I can't 100% be sure it's a replacement for 0.12's style until things get placed differently (more things to the side rather than below, such as in #24).

**Comment by dexterleng** [comment]
@nriley just shipped brighter/more legible labels in Alpha 14.

**Comment by dexterleng** [comment]
Alright, closing this now!
