### ISSUE TITLE
Search Only workflow

### ISSUE THREAD

**Issue by srikat** [dexterleng/homerow#32]
In addition to `Search & Labels` and `Labels Only (Classic)` workflows, it would be useful to have a `Search Only` option so the screen doesn't get littered with labels (when there are many, like on some webpages) making it quite messy.

**Comment by dexterleng** [comment]
Have you tried this option? I want to avoid having more than two workflow variants for ease of maintenance on my end.

![CleanShot 2023-01-21 at 11 04 52@2x](https://user-images.githubusercontent.com/34204380/213840963-a62c588a-0eca-42b3-a4f5-595708dda304.png)

**Comment by srikat** [comment]
I am looking to avoid the visual clutter of link hints and just locate elements by typing the text/type of element.

> so I may not do this.

I understand. That's alright.
