### ISSUE TITLE
Homerow deactivated once I click menu item 

### ISSUE THREAD

**Issue by argllr** [dexterleng/homerow#34]
**Describe the bug**
Homerow cannot active on the menu expended items

**Steps to reproduce the bug**
1. activate homerow, labels appear on mac menu bar 
2. type one label of the menu item and press enter, the menu expended
3. I want to activate homerow again by the hotkey, but the expended menu will close once I type anything

Is it possible add new labels to the expended menu item once I expend the menu by homerow? So I can click on the item I want.

**Comment by dexterleng** [comment]
@argllr hey, I'm choosing not to work on this due to it's complexity from my pass experience (see: https://github.com/dexterleng/homerow/issues/3#issuecomment-1274647087). I might revisit this in the future. 

I'm closing this in favour of #3.
