### ISSUE TITLE
Shortcut to select text

### ISSUE THREAD

**Issue by eproxus** [dexterleng/homerow#38]
**Is your feature suggestion related to a problem? Please describe.**
Homerow shows label for many things that are not "clickable", like text in Safari web pages for example. It would be great if items that are selectable could be selected so one could copy text from a web page without using the mouse.

**Describe the solution you'd like**
Once the item has been selected in Homerow, a shortcut like <kbd>⌥</kbd>+<kbd>Space</kbd> should mark the text as selected (or some other appropriate binding, since right click can already be achieved with <kbd>⌃</kbd>+<kbd>Space</kbd>).

**Describe alternatives you've considered**
Another shortcut for direct copy, but I think that is better left to the user using the normal OS shortcuts. The user might have other shortcuts set up to do things with selected content that could also be used after text has been selected.

**Comment by dexterleng** [comment]
Agreed, you should be able to copy text to clipboard. I would prefer a shortcut like `Command + C` though.

Closing in favour of #22.
