### ISSUE TITLE
Unable to select items in app dock

### ISSUE THREAD

**Issue by HeyBradyLang** [dexterleng/homerow#4]
Unable to use homerow to target an open application, like Steam, in the dock.

**Comment by dexterleng** [comment]
Personally I don't use the dock (use Raycast + Contexts.app), but I def can see why this is needed if you use the dock to switch/launch apps. Thanks for the suggestion @HeyBradyLang.

**Comment by dexterleng** [comment]
@HeyBradyLang You can now target and click on dock items in Alpha 8!
<img width="1392" alt="CleanShot 2022-11-05 at 18 07 44@2x" src="https://user-images.githubusercontent.com/34204380/200114592-99f2c319-af83-4840-9341-b6d7cb08b622.png">
