### ISSUE TITLE
Custom characters in hint mode

### ISSUE THREAD

**Issue by noamvokaal** [dexterleng/homerow#41]
**Describe the solution you'd like**
I’d like an option to choose custom characters for hint mode. Vimac have that option. This is especially useful for custom keyboard layout users for whom certain letters are inaccessible (such as `Q`, `C`, `X`, `Z` etc.). With this solution I’m able to mainly use my own homerow keys for hint clicks.

It would be even cooler if international characters were allowed. For an example, in the Scandinavian coutries we use `Å`, `Æ`, `Ä`, `Ø` and `Ö` a lot.

**Comment by dexterleng** [comment]
Closing in favor of #28
