### ISSUE TITLE
Does not support Chromium Contents

### ISSUE THREAD

**Issue by adithyabsk** [dexterleng/homerow#46]
**Describe the bug**

Homerow seems to work on Chrome and Firefox but doesn't seem to work on chromium. Specifically the versions installed via `brew` (e.g. `chromium`, `eloston-chromium`). To be clear, it does identify the os level items but not the in browser elements

macOS: 12.6.1
homerow version: 0.18

**Comment by dexterleng** [comment]
I'm maintaining an allowlist of Chromium app bundle ids to enable Chromium support. 

I'm going to work on a user-managed Chromium/Electron support allowlist.

**Comment by dexterleng** [comment]
I can add in their bundle ids in the meanwhile though, just pass me their bundle ids!

**Comment by adithyabsk** [comment]
@dexterleng looks like you got to it already--seems to be working for me on build `0.20`
