### ISSUE TITLE
User guide incorrect info

### ISSUE THREAD

**Issue by gohma231** [dexterleng/homerow#49]
As far as I can tell, there is no way to map the hyper key + J/K to the select the next/prefious UI element. 

![image](https://user-images.githubusercontent.com/4106435/226940933-2b1d1aeb-91c0-4140-8b19-c6d94b716e66.png)

**Comment by dexterleng** [comment]
You'll need to use Hyper Key or Karabiner Elements to do it!

![CleanShot 2023-04-07 at 16 38 18](https://user-images.githubusercontent.com/34204380/230574790-b2b1466b-04bf-4bdb-9eba-1fd2c7537c82.png)
