### ISSUE TITLE
Question about old version homerow

### ISSUE THREAD

**Issue by Acring** [dexterleng/homerow#5]
I used the old version of the app before -> https://install.appcenter.ms/users/dexterleng/apps/homerow/distribution_groups/released , and I think it is more in line with my usage habits. I used control+f to select tabs and control+j to scroll pages.
The new app puts forward a new way of interaction, but it can't meet my needs. I want to know whether the old functions will be supported in the future, and if not, can I only pay for the old app?

**Comment by sunho-lee** [comment]
> I used the old version of the app before -> https://install.appcenter.ms/users/dexterleng/apps/homerow/distribution_groups/released , and I think it is more in line with my usage habits. I used control+f to select tabs and control+j to scroll pages. The new app puts forward a new way of interaction, but it can't meet my needs. I want to know whether the old functions will be supported in the future, and if not, can I only pay for the old app?

> can i only pay for the old app
me too.

**Comment by dexterleng** [comment]
Close to merge w/ #6.
