### ISSUE TITLE
Auto click after typing the hint

### ISSUE THREAD

**Issue by khoi** [dexterleng/homerow#50]
**Is your feature suggestion related to a problem? Please describe.**
Coming from vimac, it's annoying for me to have to press an extra Enter or Space to click on the item. Can we introduce a setting to just auto-click after typing the hint?

**Comment by dexterleng** [comment]
Coming soon 👀

**Comment by dexterleng** [comment]
Just released Alpha 19. You'll need to enable the "Click automatically when label is selected" option.

![CleanShot 2023-04-07 at 17 58 08](https://user-images.githubusercontent.com/34204380/230589043-5d265fef-c75a-41b0-b6dc-56b8a6d59c3c.png)

Let me know if there's any issues!
