### ISSUE TITLE
No support for Tidal music player app

### ISSUE THREAD

**Issue by DoDoENT** [dexterleng/homerow#52]
**Describe the bug**

Buttons in Tidal music player app are not recognized.

![image](https://user-images.githubusercontent.com/158844/230098901-7b8fadd6-901a-4923-8203-449be2bb2183.png)

As you can see on the screenshot, no buttons in the app have been recognized. I'm mostly interested into the like button (the little heart), as liking the track that is currently played is literally the only thing I still need to do with mouse. Everything else is already keyboard-only for me using the combination of Vimium, SKHD, Yabai, and Karabiner Elements. Unfortunately, the tidal app itself also doesn't have the configurable shortcut for liking tracks.

**Comment by dexterleng** [comment]
Coming soon 👀

**Comment by dexterleng** [comment]
Just released Alpha 19 with Tidal support. Closing this now.
