### ISSUE TITLE
Ability to quit the app when the menu bar icon is disabled

### ISSUE THREAD

**Issue by ChiliJohnson** [dexterleng/homerow#53]
I might be missing something, but there doesn't seem to be an obvious way to quit the app when `Show icon in menu bar` is disabled. I thought maybe `cmd+q` when the Homerow Preferences pane or search bar is open would do the trick but all I get is an alert bell when I try that.

Currently it seems like, for users who don't want the menu bar icon, the procedure to quit is first open preferences, turn on the menu bar icon, click it, then quit. Then when starting up, immediately open preferences and turn off the menu bar icon again

An easy solution might be allowing `cmd+q` to quit the app (instead of triggering a bell) directly from the preferences pane or when the Homerow search palette is open. Another option could be some special string entered into the search palette? I like this option less because there is potential for a collision when searching for actual elements on screen.

**Comment by dexterleng** [comment]
@ChiliJohnson Agreed. Next update will allow you to Press Command+Q to quit when Preferences is open or when a mode is active.

**Comment by dexterleng** [comment]
Just released Alpha 19. Let me know if there's any issues!
