### ISSUE TITLE
Move (do no click) cursor on option-return

### ISSUE THREAD

**Issue by gnodar01** [dexterleng/homerow#58]
**Is your feature suggestion related to a problem? Please describe.**
vimac would move the cursor without clicking when holding down the option key and typing in the label. This was quite a useful feature.

**Describe the solution you'd like**
I would like to see in homerow move the cursor without clicking when holding `option-return`.

**Describe alternatives you've considered**
vimac, which is the predecessor of homerow

**Comment by dexterleng** [comment]
closed in favor of #51
