### ISSUE TITLE
Feature Request: [modifiers+]click

### ISSUE THREAD

**Issue by hacker-DOM** [dexterleng/homerow#7]
It would be great if there was a way to do e.g. `cmd+click`. Ideally, this would work just by:

- enter Hints mode
- hold Cmd
- enter hint letters

**Comment by choonkeat** [comment]
Does this help https://github.com/dexterleng/homerow/issues/6#issuecomment-1301556252

**Comment by dexterleng** [comment]
Yup you can do that, see: https://github.com/dexterleng/homerow#controls.
