### ISSUE TITLE
Sonoma 14.0 Beta(23A5276g) menu bar is invalid

### ISSUE THREAD

**Issue by xiaokyo** [dexterleng/homerow#74]
**Describe the bug**
Sonoma 14.0 Beta(23A5276g) menu bar is invalid

**Screenshots / video**

<img width="1800" alt="image" src="https://github.com/dexterleng/homerow/assets/22857964/81025c04-d6f4-4a98-8aeb-0da1d45dd2cd">

**Steps to reproduce the bug**

1. command + shift + space

**Comment by devnoname120** [comment]
@xiaokyo Does this bug still happen? I've been holding off upgrading to Sonoma and now the last remaining (potential) blocker is Homerow. I'm currently on Ventura and I can't live without Homerow so I only want to upgrade if I'm certain it works properly.

**Comment by xiaokyo** [comment]
> @xiaokyo Does this bug still happen? I've been holding off upgrading to Sonoma and now the last remaining (potential) blocker is Homerow. I'm currently on Ventura and I can't live without Homerow so I only want to upgrade if I'm certain it works properly.

it's not gonna happen

**Comment by devnoname120** [comment]
What do you mean with “it's not gonna happen ”?
Did @dexterleng make an official statement on that?
