### ISSUE TITLE
I would like targets for the status icons of the menu bar

### ISSUE THREAD

**Issue by quadruple-output** [dexterleng/homerow#9]
Currently, `homerow` (alpha 8) creates targets for the controls of the focussed app window, and the active desktop's menu bar. No targets are created for the status icons on the right-hand side of the menu bar.

I would like to open the submenus of status icons from the menu bar using `homerow`. My primary use cases are
- Activate the "Input Sources" menu;
- Activate the menu of my VPN connection app, so I can quickly connect or disconnect a VPN without having to use the mouse.

**Comment by bfulop** [comment]
If by any chance you have [Bartender](https://www.macbartender.com) installed, it gives you great shortcuts to access any element on your menu bar (the right side).

**Comment by quadruple-output** [comment]
Thank you for the work-around, @bfulop . I am currently using `homerow` and `vimac` (`homerow`'s predecessor) at the same time. `vimac` actually offers the status bar shortcuts I need. By opening this feature request, I wanted to increase the chances that `homerow` will become a full replacement of `vimac`, one day. I guess I should have made this more clear in the beginning.

**Comment by dexterleng** [comment]
@quadruple-output hello, labelling of the top-right menu icons is planned, as for the actual menu list itself, see #3.

**Comment by dexterleng** [comment]
Released in Alpha 11 🚀

Let me know if there are any issues.

https://twitter.com/dexterleng/status/1601872519556136960?t=2aqEMIojw73Eman25sUSzA&s=19
